services:
  publisher:
    build:
      context: .
      dockerfile: ./docker/publisher/Dockerfile
    volumes:
      - ./src:/usr/src/app
      - /path/to/data.stxm:/data/test.stxm # CHANGEME
    env_file:
      - ./docker/publisher/.env 
    environment:
      - PYTHONUNBUFFERED=1 
    depends_on:
      - subscriber

  subscriber:
    build:
      context: .
      dockerfile: ./docker/subscriber/Dockerfile
    volumes:
      - ./docker/subscriber/config.json:/usr/src/app/acme_data_cleaning/config.json
      - ./src:/usr/src/app
      - ./outputs:/outputs
    environment:
      - PYTHONUNBUFFERED=1